packages:
  - 'apps/*'
  - 'packages/*'
allowBuilds:
  '@parcel/watcher': false
  '@swc/core': false
  esbuild: true
  mongodb-memory-server: false
  sharp: true
  unrs-resolver: true
  vue-demi: false
  workerd: true
patchedDependencies:
  '@opennextjs/cloudflare@1.20.1': patches/@opennextjs__cloudflare@1.20.1.patch
